kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: project-two
  namespace: argocd
spec:
  sourceNamespaces:
    - poc2
  sourceRepos:
    - "*"
  destinations:
    - namespace: poc2
      server: https://kubernetes.default.svc
      name: in-cluster
