kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: project-one
  namespace: argocd
spec:
  sourceNamespaces:
    - poc1
  sourceRepos:
    - "*"
  destinations:
    - namespace: poc1
      server: https://kubernetes.default.svc
      name: in-cluster
