apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argopoc1
  namespace: poc1
spec:
  project: project-one
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://github.com/jagpreetstamber/argo-poc.git
    path: poc/charts/testchart
    targetRevision: HEAD
    helm:
      releaseName: argopoc1
      valuesObject:
        image:
          acr: cdpx10245db0189c43d396893f4497bf2395test.azurecr.io
          tag: 1.0.36
  destination:
    server: "https://kubernetes.default.svc"
    namespace: poc1
