apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argopoc1
  namespace: poc1
spec:
  project: default
  source:
    chart: argopoc1
    repoURL: https://github.com/jagpreetstamber/argo-poc/tree/main/poc/charts/testchart
    targetRevision: 1.0.18
    helm:
      releaseName: argopoc1
      valuesObject:
        ingress:
          image:
            acr: cdpx10245db0189c43d396893f4497bf2395test.azurecr.io
            tag: 1.0.18
  destination:
    server: "https://kubernetes.default.svc"
    namespace: poc1