apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argopoc2
  namespace: poc2
spec:
  project: project-two
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://github.com/jagpreetstamber/argo-poc.git
    path: poc/charts/testchart
    targetRevision: HEAD
    helm:
      releaseName: argopoc2
      valuesObject:
        image:
          acr: cdpx10245db0189c43d396893f4497bf2395test.azurecr.io
          tag: 1.0.18
        namespace: poc3
  destination:
    server: "https://kubernetes.default.svc"
    namespace: poc2
