apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.Namespace }}
  name: {{ .Chart.Name }}-deployment
  labels:
    app: argo-poc
    namespace: {{ .Values.Namespace }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argo-poc
      namespace: {{ .Values.Namespace }}
  template:
    metadata:
      labels:
        app: argo-poc
        namespace: {{ .Values.Namespace }}
    spec:
      containers:
      - name: argo-poc
        image: "{{ .Values.image.acr }}/{{ .Values.image.path }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 700m
          limits:
            cpu: 700m
            memory: 1Gi
        env:
        - name: "DEMO_MESSAGE"
          value: "I am deployed with Flux using HelmRelease and Ev2!"