apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.Namespace }}
spec:
  selector:
    app: argo-poc
    namespace: {{ .Values.Namespace }}
  ports:
  - port: 80
    targetPort: 5000
